service: serverless

provider:
    name: aws
    runtime: nodejs12.x

functions:
    test:
        handler: ./dist/index.handler
        name: hello-world
        events: 
            - hhtpApi:
                method: GET
                path: /
