service: serverless

provider:
    name: aws
    runtime: nodejs12.x

functions:
    testStart:
        handler: ./dist/index.handler
        name: test-start
        events: 
            - http: GET hello
        destinations:
            onSuccess: testSuccess
    testSuccess:
        name: test-success
        handler: ./dist/index.lambda

