# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: pre-releases

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pre-release:
    name: "Pre Release"

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
        - uses: actions/checkout@v2
        - name: Setup SSH Keys and known_hosts
          env:
              SSH_AUTH_SOCK: /tmp/ssh_agent.sock
              run: |
                  mkdir -p ~/.ssh
                  ssh-keyscan github.com >> ~/.ssh/known_hosts
                  ssh-agent -a $SSH_AUTH_SOCK > /dev/null
                  ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        - uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}
        - run: npm install && npm run build
        - uses: "marvinpinto/action-automatic-releases@latest"
          with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "latest"
            prerelease: true
            title: "Development Build"
            files: ./dist
  
